©2023 Sun Haoze. All rights reserved.
echo -e "welcome to use toolkit \n"
echo -e "Copr. 2023 Haoze Sun \n"
echo -e "wait 10 sec please  \n"
sleep 10
clear
echo -e "gitting public NTP sever on Interent \n"
ping -c 1 ntp.ntsc.ac.cn
ping -c 1 cn.ntp.org.cn
ping -c 1 edu.ntp.org.cn
ping -c 1 hk.ntp.org.cn
ping -c 1 tw.ntp.org.cn
ping -c 1 jp.ntp.org.cn
ping -c 1 kr.ntp.org.cn
ping -c 1 sgp.ntp.org.cn
ping -c 1 us.ntp.org.cn
ping -c 1 de.ntp.org.cn
ping -c 1 ina.ntp.org.cn
ping -c 1 ntp1.nim.ac.cn
ping -c 1 ntp2.nim.ac.cn
ping -c 1 0.pool.ntp.org
ping -c 1 1.pool.ntp.org
ping -c 1 2.pool.ntp.org
ping -c 1 3.pool.ntp.org
ping -c 1 0.asia.pool.ntp.org
ping -c 1 1.asia.pool.ntp.org
ping -c 1 2.asia.pool.ntp.org
ping -c 1 3.asia.pool.ntp.org
ping -c 1 0.ae.pool.ntp.org
ping -c 1 1.ae.pool.ntp.org
ping -c 1 2.ae.pool.ntp.org
ping -c 1 3.ae.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.az.pool.ntp.org
ping -c 1 1.az.pool.ntp.org
ping -c 1 2.az.pool.ntp.org
ping -c 1 3.az.pool.ntp.org
ping -c 1 0.bd.pool.ntp.org
ping -c 1 1.bd.pool.ntp.org
ping -c 1 2.bd.pool.ntp.org
ping -c 1 3.bd.pool.ntp.org
ping -c 1 0.bh.pool.ntp.org
ping -c 1 1.bh.pool.ntp.org
ping -c 1 2.bh.pool.ntp.org
ping -c 1 3.bh.pool.ntp.org
ping -c 1 0.bn.pool.ntp.org
ping -c 1 1.bn.pool.ntp.org
ping -c 1 2.bn.pool.ntp.org
ping -c 1 3.bn.pool.ntp.org
ping -c 1 0.bt.pool.ntp.org
ping -c 1 1.bt.pool.ntp.org
ping -c 1 2.bt.pool.ntp.org
ping -c 1 3.bt.pool.ntp.org
ping -c 1 0.cc.pool.ntp.org
ping -c 1 1.cc.pool.ntp.org
ping -c 1 2.cc.pool.ntp.org
ping -c 1 3.cc.pool.ntp.org
ping -c 1 0.cn.pool.ntp.org
ping -c 1 1.cn.pool.ntp.org
ping -c 1 2.cn.pool.ntp.org
ping -c 1 3.cn.pool.ntp.org
ping -c 1 0.ge.pool.ntp.org
ping -c 1 1.ge.pool.ntp.org
ping -c 1 2.ge.pool.ntp.org
ping -c 1 3.ge.pool.ntp.org
ping -c 1 0.hk.pool.ntp.org
ping -c 1 1.hk.pool.ntp.org
ping -c 1 2.hk.pool.ntp.org
ping -c 1 3.hk.pool.ntp.org
ping -c 1 0.id.pool.ntp.org
ping -c 1 1.id.pool.ntp.org
ping -c 1 2.id.pool.ntp.org
ping -c 1 3.id.pool.ntp.org
ping -c 1 0.il.pool.ntp.org
ping -c 1 1.il.pool.ntp.org
ping -c 1 2.il.pool.ntp.org
ping -c 1 3.il.pool.ntp.org
ping -c 1 0.in.pool.ntp.org
ping -c 1 1.in.pool.ntp.org
ping -c 1 2.in.pool.ntp.org
ping -c 1 3.in.pool.ntp.org
ping -c 1 0.io.pool.ntp.org
ping -c 1 1.io.pool.ntp.org
ping -c 1 2.io.pool.ntp.org
ping -c 1 3.io.pool.ntp.org
ping -c 1 0.iq.pool.ntp.org
ping -c 1 1.iq.pool.ntp.org
ping -c 1 2.iq.pool.ntp.org
ping -c 1 3.iq.pool.ntp.org
ping -c 1 0.ir.pool.ntp.org
ping -c 1 1.ir.pool.ntp.org
ping -c 1 2.ir.pool.ntp.org
ping -c 1 3.ir.pool.ntp.org
ping -c 1 0.jo.pool.ntp.org
ping -c 1 1.jo.pool.ntp.org
ping -c 1 2.jo.pool.ntp.org
ping -c 1 3.jo.pool.ntp.org
ping -c 1 0.jp.pool.ntp.org
ping -c 1 1.jp.pool.ntp.org
ping -c 1 2.jp.pool.ntp.org
ping -c 1 3.jp.pool.ntp.org
ping -c 1 0.kg.pool.ntp.org
ping -c 1 1.kg.pool.ntp.org
ping -c 1 2.kg.pool.ntp.org
ping -c 1 3.kg.pool.ntp.org
ping -c 1 0.kh.pool.ntp.org
ping -c 1 1.kh.pool.ntp.org
ping -c 1 2.kh.pool.ntp.org
ping -c 1 3.kh.pool.ntp.org
ping -c 1 0.kp.pool.ntp.org
ping -c 1 1.kp.pool.ntp.org
ping -c 1 2.kp.pool.ntp.org
ping -c 1 3.kp.pool.ntp.org
ping -c 1 0.kr.pool.ntp.org
ping -c 1 1.kr.pool.ntp.org
ping -c 1 2.kr.pool.ntp.org
ping -c 1 3.kr.pool.ntp.org
ping -c 1 0.kw.pool.ntp.org
ping -c 1 1.kw.pool.ntp.org
ping -c 1 2.kw.pool.ntp.org
ping -c 1 3.kw.pool.ntp.org
ping -c 1 0.kz.pool.ntp.org
ping -c 1 1.kz.pool.ntp.org
ping -c 1 2.kz.pool.ntp.org
ping -c 1 3.kz.pool.ntp.org
ping -c 1 0.kh.pool.ntp.org
ping -c 1 1.kh.pool.ntp.org
ping -c 1 2.kh.pool.ntp.org
ping -c 1 3.kh.pool.ntp.org
ping -c 1 0.kp.pool.ntp.org
ping -c 1 1.kp.pool.ntp.org
ping -c 1 2.kp.pool.ntp.org
ping -c 1 3.kp.pool.ntp.org
ping -c 1 0.kr.pool.ntp.org
ping -c 1 1.kr.pool.ntp.org
ping -c 1 2.kr.pool.ntp.org
ping -c 1 3.kr.pool.ntp.org
ping -c 1 0.kw.pool.ntp.org
ping -c 1 1.kw.pool.ntp.org
ping -c 1 2.kw.pool.ntp.org
ping -c 1 3.kw.pool.ntp.org
ping -c 1 0.kz.pool.ntp.org
ping -c 1 1.kz.pool.ntp.org
ping -c 1 2.kz.pool.ntp.org
ping -c 1 3.kz.pool.ntp.org
ping -c 1 0.la.pool.ntp.org
ping -c 1 1.la.pool.ntp.org
ping -c 1 2.la.pool.ntp.org
ping -c 1 3.la.pool.ntp.org
ping -c 1 0.lb.pool.ntp.org
ping -c 1 1.lb.pool.ntp.org
ping -c 1 2.lb.pool.ntp.org
ping -c 1 3.lb.pool.ntp.org
ping -c 1 0.lk.pool.ntp.org
ping -c 1 1.lk.pool.ntp.org
ping -c 1 2.lk.pool.ntp.org
ping -c 1 3.lk.pool.ntp.org
ping -c 1 0.mm.pool.ntp.org
ping -c 1 1.mm.pool.ntp.org
ping -c 1 2.mm.pool.ntp.org
ping -c 1 3.mm.pool.ntp.org
ping -c 1 0.mn.pool.ntp.org
ping -c 1 1.mn.pool.ntp.org
ping -c 1 2.mn.pool.ntp.org
ping -c 1 3.mn.pool.ntp.org
ping -c 1 0.mo.pool.ntp.org
ping -c 1 1.mo.pool.ntp.org
ping -c 1 2.mo.pool.ntp.org
ping -c 1 3.mo.pool.ntp.org
ping -c 1 0.mv.pool.ntp.org
ping -c 1 1.mv.pool.ntp.org
ping -c 1 2.mv.pool.ntp.org
ping -c 1 3.mv.pool.ntp.org
ping -c 1 0.my.pool.ntp.org
ping -c 1 1.my.pool.ntp.org
ping -c 1 2.my.pool.ntp.org
ping -c 1 3.my.pool.ntp.org
ping -c 1 0.np.pool.ntp.org
ping -c 1 1.np.pool.ntp.org
ping -c 1 2.np.pool.ntp.org
ping -c 1 3.np.pool.ntp.org
ping -c 1 0.om.pool.ntp.org
ping -c 1 1.om.pool.ntp.org
ping -c 1 2.om.pool.ntp.org
ping -c 1 3.om.pool.ntp.org
ping -c 1 0.ph.pool.ntp.org
ping -c 1 1.ph.pool.ntp.org
ping -c 1 2.ph.pool.ntp.org
ping -c 1 3.ph.pool.ntp.org
ping -c 1 0.pk.pool.ntp.org
ping -c 1 1.pk.pool.ntp.org
ping -c 1 2.pk.pool.ntp.org
ping -c 1 3.pk.pool.ntp.org
ping -c 1 0.ps.pool.ntp.org
ping -c 1 1.ps.pool.ntp.org
ping -c 1 2.ps.pool.ntp.org
ping -c 1 3.ps.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 0.af.pool.ntp.org
ping -c 1 1.af.pool.ntp.org
ping -c 1 2.af.pool.ntp.org
ping -c 1 3.af.pool.ntp.org
ping -c 1 
ping -c 1 