©2023 Sun Haoze. All rights reserved.
echo -e "welcome to use toolkit \n"
echo -e "Copr. 2023 Haoze Sun \n"
echo -e "wait 10 sec please  \n"
sleep 10
clear
echo -e "gitting public NTP sever on Interent \n"
ping -c 1 ntp.ntsc.ac.cn
ping -c 1 cn.ntp.org.cn
ping -c 1 edu.ntp.org.cn
ping -c 1 hk.ntp.org.cn
ping -c 1 tw.ntp.org.cn
ping -c 1 jp.ntp.org.cn
ping -c 1 kr.ntp.org.cn
ping -c 1 sgp.ntp.org.cn
ping -c 1 us.ntp.org.cn
ping -c 1 de.ntp.org.cn
ping -c 1 ina.ntp.org.cn
ping -c 1 ntp1.nim.ac.cn
ping -c 1 ntp2.nim.ac.cn
ping -c 1 0.pool.ntp.org
ping -c 1 1.pool.ntp.org
ping -c 1 2.pool.ntp.org
ping -c 1 3.pool.ntp.org
ping -c 1 0.asia.pool.ntp.org
ping -c 1 1.asia.pool.ntp.org
ping -c 1 2.asia.pool.ntp.org
ping -c 1 3.asia.pool.ntp.org
ping -c 1 0.africa.pool.ntp.org
ping -c 1 1.africa.pool.ntp.org
ping -c 1 2.africa.pool.ntp.org
ping -c 1 3.africa.pool.ntp.org
ping -c 1 0.europe.pool.ntp.org
ping -c 1 1.europe.pool.ntp.org
ping -c 1 2.europe.pool.ntp.org
ping -c 1 3.europe.pool.ntp.org
ping -c 1 0.north-america.pool.ntp.org 
ping -c 1 1.north-america.pool.ntp.org 
ping -c 1 2.north-america.pool.ntp.org 
ping -c 1 3.north-america.pool.ntp.org 
ping -c 1 0.oceania.pool.ntp.org 
ping -c 1 1.oceania.pool.ntp.org 
ping -c 1 2.oceania.pool.ntp.org 
ping -c 1 3.oceania.pool.ntp.org
ping -c 1 0.south-america.pool.ntp.org 
ping -c 1 1.south-america.pool.ntp.org 
ping -c 1 2.south-america.pool.ntp.org 
ping -c 1 3.south-america.pool.ntp.org
ping -c 1 time.pool.aliyun.com
ping -c 1 time1.aliyun.com
ping -c 1 time2.aliyun.com
ping -c 1 time3.aliyun.com
ping -c 1 time4.aliyun.com
ping -c 1 time5.aliyun.com
ping -c 1 time6.aliyun.com
ping -c 1 time7.aliyun.com
ping -c 1 time1.cloud.tencent.com
ping -c 1 time2.cloud.tencent.com
ping -c 1 time3.cloud.tencent.com
ping -c 1 time4.cloud.tencent.com
ping -c 1 time5.cloud.tencent.com
ping -c 1 ntp.sjtu.edu.cn
ping -c 1 ntp.neu.edu.cn
ping -c 1 ntp.bupt.edu.cn
ping -c 1 ntp.shu.edu.cn
ping -c 1 ntp.myhuaweicloud.com
ping -c 1 time1.google.com
ping -c 1 time2.google.com
ping -c 1 time3.google.com
ping -c 1 time4.google.com
ping -c 1 time.apple.com
ping -c 1 time1.apple.com
ping -c 1 time2.apple.com
ping -c 1 time3.apple.com
ping -c 1 time4.apple.com
ping -c 1 time5.apple.com
ping -c 1 time6.apple.com
ping -c 1 time7.apple.com
ping -c 1 time.cloudflare.com
ping -c 1 time.windows.com
ping -c 1 time.nist.gov
ping -c 1 time-nw.nist.gov
ping -c 1 time-a.nist.gov
ping -c 1 time-b.nist.gov